### ISSUE TITLE
Exception when searching for stations

### ISSUE THREAD

**Issue by mitchpaulus** [aaronpenne/get_noaa_ghcn_data#1] opened 2018-04-18 15:00 UTC
I'm getting the following exception when searching for stations, using the example from the screenshot on the README page. It's having problems doing some casting. I'm running this on the Windows Subsystem for Linux, so I know my setup is not typical, not sure if that would have anything to do with it. 

Appreciate any help. Would be awesome to get this working, thanks!

```
230-****** WARNING ** WARNING ** WARNING ** WARNING ** WARNING ******
 ** This is a United States Department of Commerce computer     **
 ** system, which may be accessed and used only for             **
 ** official Government business by authorized personnel.       **
 ** Unauthorized access or use of this computer system may      **
 ** subject violators to criminal, civil, and/or administrative **
 ** action.  All information on this computer system may be     **
 ** intercepted, recorded, read, copied, and disclosed by and   **
 ** to authorized personnel for official purposes, including    **
 ** criminal investigations.  Access or use of this computer    **
 ** system by any person, whether authorized or unauthorized,   **
 ** constitutes consent to these terms.                         **
 ****** WARNING ** WARNING ** WARNING ** WARNING ** WARNING ******
230 Anonymous access granted, restrictions apply

Enter station name, full or partial. (ex. Washington, san fran, USC): chico

Traceback (most recent call last):
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1655, in _cast_types
    values = astype_nansafe(values, cast_type, copy=True)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/core/dtypes/cast.py", line 703, in astype_nansafe
    return arr.astype(dtype)
ValueError: could not convert string to float: 'GSN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_noaa_ghcn_data.py", line 17, in <module>
    station_id = get_station_id.get_station_id(ftp)
  File "/mnt/c/Users/mpaulus/get_noaa_ghcn_data-master/get_station_id.py", line 88, in get_station_id
    df = pd.read_fwf(local_full_path, widths=widths, names=names, dtype=dtype, header=None)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 741, in read_fwf
    return _read(filepath_or_buffer, kwds)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 2269, in read
    data = self._convert_data(data)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 2338, in _convert_data
    clean_conv, clean_dtypes)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1562, in _convert_to_ndarrays
    cvals = self._cast_types(cvals, cast_type, c)
  File "/home/mpaulus/.local/lib/python3.5/site-packages/pandas/io/parsers.py", line 1658, in _cast_types
    "type %s" % (column, cast_type))
ValueError: Unable to convert column LATITUDE to type <class 'float'>
```

**Comment by aaronpenne** [comment] 2018-04-18 15:42
Thanks for pointing this out. I confirmed that this issue does not occur with my setup, so I'm not sure if my fix will solve your problem. I changed all of the dtypes to `str` before reading the .dly file with `pd.read_fwf` since the floats are not needed. Give it a shot and let me know what happens.

**Comment by mitchpaulus** [comment] 2018-04-18 17:53
Your fix resolved the issue. I ran into another issue when searching for the stations, the order of the column names was getting messed up. I've made a PR (#2) to fix it, feel free to pull it in or just fix it yourself. You can close this issue. Thanks!

**Comment by aaronpenne** [comment] 2018-04-18 17:55
Sounds good, closing this issue. Hope the tool works well for you.

**Closed as completed by aaronpenne** 2018-04-18 17:55 UTC
